version: "3.8"

services:
  backend:
    build: ./backend
    image: aws-sample-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: "http://localhost:3000/"
    image: aws-sample-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
